### ISSUE TITLE
Protection in log scale for negative bin content

### ISSUE THREAD

**Issue by rmadar** [rmadar/tree-gonalyzer#47]
### Problem

This can happen when the binning is very fine and/or the statistics is very low, *and* when event might have negative weights (typical in NLO calculations). This crashes in case of log scale for the y-axis, so a protection should be added. For example:

![image](https://user-images.githubusercontent.com/30081646/88851621-47c88780-d1ed-11ea-8734-556ea47f968d.png)
 
will leads to the following error message in log scale:
```
panic: Values must be greater than 0 for a log scale.

goroutine 1202 [running]:
gonum.org/v1/plot.LogTicks.Ticks(0xc03082e31d099e4f, 0x40ac1368b65e223a, 0x10, 0x1, 0x1)
	/users/divers/atlas/madar/go/pkg/mod/gonum.org/v1/plot@v0.7.1-0.20200701071522-4260761de856/axis.go:523 +0x5c0
gonum.org/v1/plot.verticalAxis.size(0xc03082e31d099e4f, 0x40ac1368b65e223a, 0xaa32f8, 0x10, 0x4014000000000000, 0xf377a0, 0xc0004e64f8, 0x402c000000000000, 0xa9f106, 0x9, ...)
	/users/divers/atlas/madar/go/pkg/mod/gonum.org/v1/plot@v0.7.1-0.20200701071522-4260761de856/axis.go:332 +0x85
gonum.org/v1/plot.(*Plot).DataCanvas(0xc0001ded80, 0xf59820, 0xc000914cf0, 0x4018000000000000, 0x4064000000000000, 0x407a000000000000, 0x4071a78000000000, 0x0, 0x0, 0x0, ...)

[...]
``` 

### Proposed solutions

  1. Set the bin content of histograms to a minimum (positive) value for bins with negative content. Not sure it's possible with the current `hbook.H1D` or `hplot.H1D`. So, maybe option 2 is better ... 
  2. Ignore these bins when plotting in log scale - but this should be done at the level of https://github.com/go-hep/hep

**Comment by rmadar** [comment]
Now solved, closing
